In [1]:
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parents[2]))
from utils.helpers import save_csv_file, anonymize_IDs

## Prepare raw data til analysis

### Oblig 3 2025

In [2]:
df_oblig3 = pd.read_excel('../data/raw_data/oblig3-Iuliia.xlsx', engine='openpyxl')

In [3]:
df_oblig3.head()

,$submission_id,$created,Brukernavn,Vil du oppgi ditt kjønn,Hvilke studieprogram går du på?,NOR-port,XOR-port,AND-port,Buffer-port,Lampe og bryter,...,Kun bruke stort RAM som er rask og med høy lagringsplass,Kun bruke cache-minne da det er raskt,La CPUen håndtere all minnehåndtering,DL´ &#43; VN,(D&#43;L)(V&#43;N),DV(L´ &#43; N),DLVN,D &#43; L &#43; V &#43; N,Gir du oss samtykke til å kunne se hvordan dine svar her er i forhold til eksamensresultatet ditt?,$answer_time_ms
0,38879379,2025-10-30 16:30:10,NaN,Kvinne,MAKI,75 %,25 %,0 %,0 %,0 %,...,50 %,50 %,0 %,75 %,25 %,0 %,0 %,0 %,Ja,536319
1,38880096,2025-10-30 17:19:30,NaN,Mann,DESIGN,75 %,75 %,75 %,0 %,0 %,...,50 %,50 %,25 %,25 %,100 %,25 %,25 %,25 %,Ja,336450
2,38881410,2025-10-30 19:11:30,NaN,Mann,MAKI,100 %,0 %,0 %,0 %,0 %,...,0 %,0 %,0 %,100 %,0 %,0 %,0 %,0 %,Ja,7775151
3,38882239,2025-10-30 20:33:42,NaN,Mann,ROBOTIKK,25 %,0 %,75 %,0 %,0 %,...,25 %,0 %,0 %,25 %,25 %,25 %,25 %,25 %,Ja,4063926
4,38882402,2025-10-30 20:48:29,NaN,Mann,MAKI,100 %,0 %,0 %,0 %,0 %,...,50 %,0 %,0 %,100 %,0 %,0 %,0 %,0 %,Ja,807371

In [4]:
df_oblig3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 52 columns):
 #   Column                                                                                              Non-Null Count  Dtype
---  ------                                                                                              --------------  -----
 0   $submission_id                                                                                      370 non-null    int64
 1   $created                                                                                            370 non-null    datetime64[ns]
 2   Brukernavn                                                                                          0 non-null      float64
 3   Vil du oppgi ditt kjønn                                                                             370 non-null    object
 4   Hvilke studieprogram går du på?                                                                     370 non-null    object
 5   NOR-port                                                                                            370 non-null    object
 6   XOR-port                                                                                            370 non-null    object
 7   AND-port                                                                                            370 non-null    object
 8   Buffer-port                                                                                         370 non-null    object
 9   Lampe og bryter                                                                                     370 non-null    object
 10  Port-nivå                                                                                           370 non-null    object
 11  Mikroarkitektur (datapath/kontroller)                                                               370 non-null    object
 12  Instruksjonssett-arkitektur (ISA)                                                                   370 non-null    object
 13  Systemnivå (nettverk/datasenter)                                                                    370 non-null    object
 14  KI-modeller som ChatGPT                                                                             370 non-null    object
 15  For å balansere hastighet, kapasitet og kostnad                                                     370 non-null    object
 16  For å spare strøm                                                                                   370 non-null    object
 17  For å gjøre datamaskinen større og mer imponerende                                                  370 non-null    object
 18  Fordi alle minnetyper har samme hastighet                                                           370 non-null    object
 19  Fordi man kan ha flere trinn i pipeline                                                             370 non-null    object
 20  A                                                                                                   370 non-null    object
 21  B                                                                                                   370 non-null    object
 22  AB                                                                                                  370 non-null    object
 23  A´                                                                                                  370 non-null    object
 24  B´                                                                                                  370 non-null    object
 25  Full-adder håndterer mente fra forrige bit-posisjon                                                 370 non-null    object
 26  Full-adder kan håndtere negative tall                                                               370 non-null    object
 27  Full-adder bruker mer strøm                                                                         370 non-null    object
 28  Full-adder er raskere enn halv-adder                                                                370 non-null    object
 29  Halv-adder kan bare brukes med 4-bits tall                                                          370 non-null    object
 30  0.5 ns                                                                                              370 non-null    object
 31  0.5 us                                                                                              370 non-null    object
 32  0.5 s                                                                                               370 non-null    object
 33  2 ns                                                                                                370 non-null    object
 34  2 s                                                                                                 370 non-null    object
 35  Økt gjennomstrømning                                                                                370 non-null    object
 36  Redusert forsinkelse                                                                                370 non-null    object
 37  Mindre strømforbruk per instruksjon                                                                 370 non-null    object
 38  Mulighet til å kjøre forskjellige programmer samtidig                                               370 non-null    object
 39  Automatisk feilretting i instruksjoner                                                              370 non-null    object
 40  Kombinere liten SSD med stort RAM og intelligent cache-håndtering                                   370 non-null    object
 41  Kun bruke harddisk som er billig og energieffektiv                                                  370 non-null    object
 42  Kun bruke stort RAM som er rask og med høy lagringsplass                                            370 non-null    object
 43  Kun bruke cache-minne da det er raskt                                                               370 non-null    object
 44  La CPUen håndtere all minnehåndtering                                                               370 non-null    object
 45  DL´ &#43; VN                                                                                        370 non-null    object
 46  (D&#43;L)(V&#43;N)                                                                                  370 non-null    object
 47  DV(L´ &#43; N)                                                                                      370 non-null    object
 48  DLVN                                                                                                370 non-null    object
 49  D &#43; L &#43; V &#43; N                                                                           370 non-null    object
 50  Gir du oss samtykke til å kunne se hvordan dine svar her er i forhold til eksamensresultatet ditt?  370 non-null    object
 51  $answer_time_ms                                                                                     370 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(48)
memory usage: 150.4+ KB

In [5]:
df_oblig3 = df_oblig3.drop(columns=['Brukernavn'])

In [6]:
# Remove rows where the consent column is 'Nei´]
df_oblig3 = df_oblig3[df_oblig3['Gir du oss samtykke til å kunne se hvordan dine svar her er i forhold til eksamensresultatet ditt?'] == 'Ja']
anonymize_IDs(df_oblig3, '$submission_id')

In [7]:
df_oblig3 = df_oblig3.rename(columns={'$submission_id' : 'kandidatnr'})
df_oblig3 = df_oblig3.rename(columns={'$created' : 'created'})
df_oblig3 = df_oblig3.rename(columns={'Vil du oppgi ditt kjønn' : 'Kjønn'})
df_oblig3['Kjønn'] = df_oblig3['Kjønn'].replace({'Ønsker ikke å oppgi': 'Ukjent'})
df_oblig3 = df_oblig3.rename(columns={'Hvilke studieprogram går du på?' : 'Studieprogram'})
df_oblig3['Studieprogram'] = df_oblig3['Studieprogram'].replace({'Ønsker ikke å oppgi': 'Ukjent'})
df_oblig3 = df_oblig3.rename(columns={'Gir du oss samtykke til å kunne se hvordan dine svar her er i forhold til eksamensresultatet ditt?' : 'Samtykke'})
df_oblig3 = df_oblig3.rename(columns={'$answer_time_ms' : 'Answer_time_ms'})
df_oblig3 = df_oblig3.rename(columns={'DL´ &#43; VN' : 'DL´ + VN'})
df_oblig3 = df_oblig3.rename(columns={'(D&#43;L)(V&#43;N)' : '(D + L)(V + N)'})
df_oblig3 = df_oblig3.rename(columns={'DV(L´ &#43; N)' : 'DV(L´ + N)'})
df_oblig3 = df_oblig3.rename(columns={'D &#43; L &#43; V &#43; N' : 'D + L + V + N'})

In [8]:
df_oblig3.head()

,kandidatnr,created,Kjønn,Studieprogram,NOR-port,XOR-port,AND-port,Buffer-port,Lampe og bryter,Port-nivå,...,Kun bruke stort RAM som er rask og med høy lagringsplass,Kun bruke cache-minne da det er raskt,La CPUen håndtere all minnehåndtering,DL´ + VN,(D + L)(V + N),DV(L´ + N),DLVN,D + L + V + N,Samtykke,Answer_time_ms
0,211,2025-10-30 16:30:10,Kvinne,MAKI,75 %,25 %,0 %,0 %,0 %,25 %,...,50 %,50 %,0 %,75 %,25 %,0 %,0 %,0 %,Ja,536319
1,28,2025-10-30 17:19:30,Mann,DESIGN,75 %,75 %,75 %,0 %,0 %,75 %,...,50 %,50 %,25 %,25 %,100 %,25 %,25 %,25 %,Ja,336450
2,234,2025-10-30 19:11:30,Mann,MAKI,100 %,0 %,0 %,0 %,0 %,100 %,...,0 %,0 %,0 %,100 %,0 %,0 %,0 %,0 %,Ja,7775151
3,212,2025-10-30 20:33:42,Mann,ROBOTIKK,25 %,0 %,75 %,0 %,0 %,50 %,...,25 %,0 %,0 %,25 %,25 %,25 %,25 %,25 %,Ja,4063926
4,3,2025-10-30 20:48:29,Mann,MAKI,100 %,0 %,0 %,0 %,0 %,75 %,...,50 %,0 %,0 %,100 %,0 %,0 %,0 %,0 %,Ja,807371

In [9]:
save_csv_file(df_oblig3, 'oblig3', '../data/cleaned_csv_files/')

✅ DataFrame saved as: ../data/cleaned_csv_files/oblig3.csv

## Read raw data files, convert it to pickle format and save in ../data/pickle_files with save_pickle_file(df, name, path)

In [10]:
# df_IN1020_2024 = pd.read_excel('../data/raw_data/IN1020_H24.xlsx', engine='openpyxl')
# save_pickle_file(df_IN1020_2024, 'IN1020_2024', '../data/pickle_files/')

In [11]:
# df_IN1020_2023 = pd.read_excel('../data/raw_data/IN1020_H23.xlsx', engine='openpyxl')
# save_pickle_file(df_IN1020_2023, 'IN1020_2023', '../data/pickle_files/')

In [12]:
# df_IN2120_2024 = pd.read_excel('../data/raw_data/IN2120_H24.xlsx', engine='openpyxl')
# save_pickle_file(df_IN2120_2024, 'IN2120_2024', '../data/pickle_files/')